export const packageName = "@acos/contracts" as const;

export {
  ERROR_CODES,
  ProblemJsonSchema,
  PROBLEM_TYPE_BASE,
  problemFor,
  type ErrorCode,
  type ProblemJson,
} from "./errors.js";
export {
  HealthResponseSchema,
  DependencyStatusSchema,
  type HealthResponse,
  type DependencyStatus,
} from "./health.js";
export {
  SessionUserSchema,
  SetupStatusSchema,
  SetupRequestSchema,
  LoginRequestSchema,
  LoginResponseSchema,
  TotpRequiredResponseSchema,
  PatCreateRequestSchema,
  PatCreatedSchema,
  PatListItemSchema,
  TotpEnableRequestSchema,
  TotpEnableResponseSchema,
  TotpConfirmRequestSchema,
  TotpDisableRequestSchema,
  OkSchema,
  type SessionUser,
} from "./auth.js";
export {
  CompanySchema,
  CreateCompanyRequestSchema,
  CompanySettingsSchema,
  UpdateCompanySettingsRequestSchema,
  type Company,
  type CompanySettings,
} from "./companies.js";
export {
  UnitKindSchema,
  EdgeKindSchema,
  OrgUnitSchema,
  CreateOrgUnitRequestSchema,
  MoveOrgUnitRequestSchema,
  ArchiveOrgUnitResponseSchema,
  PositionSchema,
  CreatePositionRequestSchema,
  OrgEdgeSchema,
  CreateOrgEdgeRequestSchema,
  EscalationChainSchema,
  TeamRosterEntrySchema,
  type OrgUnit,
  type Position,
  type OrgEdge,
  type EscalationChain,
} from "./org.js";
export {
  EventActorSchema,
  EventSchema,
  EventListQuerySchema,
  EventListResponseSchema,
  EventReplayQuerySchema,
  EventReplayResponseSchema,
  type Event,
  type EventListResponse,
  type EventReplayResponse,
} from "./events.js";
export {
  parseTopic,
  ClientOpSchema,
  SubscribeOpSchema,
  ResumeOpSchema,
  UnsubscribeOpSchema,
  PingOpSchema,
  HelloFrameSchema,
  SubOkFrameSchema,
  ReplayDoneFrameSchema,
  EventsDataFrameSchema,
  TerminalFrameSchema,
  TerminalDataFrameSchema,
  PresenceSnapshotFrameSchema,
  GapFrameSchema,
  PongFrameSchema,
  ErrorFrameSchema,
  ServerControlFrameSchema,
  WS_ERROR_CODES,
  WS_CLOSE_CODES,
  type TopicKind,
  type ParsedTopic,
  type ClientOp,
  type ServerControlFrame,
  type EventsDataFrame,
} from "./realtime.js";
export {
  RUNTIME_EVENT_TYPES,
  RuntimeEventSchema,
  RUNTIME_SUBJECT_PREFIX,
  runtimeSubjectFor,
  type RuntimeEvent,
  type RuntimeEventType,
} from "./runtime.js";
export {
  ChannelKindSchema,
  ChannelSchema,
  MessageKindSchema,
  MessageSchema,
  SendMessageRequestSchema,
  CreateDmRequestSchema,
  ChannelMemberSchema,
  type Channel,
  type Message,
} from "./comms.js";
export {
  TASK_NEXT_STATUSES,
  TaskKindSchema,
  TaskPrioritySchema,
  TaskStatusSchema,
  TaskRiskLevelSchema,
  TaskSchema,
  CreateTaskRequestSchema,
  UpdateTaskRequestSchema,
  TaskTransitionRequestSchema,
  ArchiveTaskRequestSchema,
  CreateDirectiveRequestSchema,
  TopExecutiveResponseSchema,
  TaskListQuerySchema,
  CreateDependencyRequestSchema,
  TaskDependencySchema,
  TaskDependenciesResponseSchema,
  CreateAssignmentRequestSchema,
  TaskAssignmentSchema,
  TaskTreeNodeSchema,
  type Task,
  type TaskAssignment,
  type TaskDependency,
  type TaskTreeNode,
} from "./tasks.js";
export {
  CellSchema,
  OfficeDeskSchema,
  OfficeZoneSchema,
  OfficeLayoutSchema,
  PRESENCE_BADGES,
  PresenceBadgeSchema,
  AvatarMovedSchema,
  InteractionStartedSchema,
  InteractionEndedSchema,
  StatusChangedSchema,
  OfficeInstructionSchema,
  PresenceAgentSchema,
  PresenceStateSchema,
  type Cell,
  type OfficeLayout,
  type OfficeZone,
  type OfficeDesk,
  type PresenceBadge,
  type OfficeInstruction,
  type PresenceState,
  type PresenceAgent,
} from "./office.js";
export {
  RealtimeClient,
  type CursorStore,
  type WebSocketLike,
  type RealtimeStatus,
  type FrameMeta,
  type FrameHandler,
  type RealtimeClientOptions,
} from "./realtime-client.js";
export {
  IsolationLevelSchema,
  WorkspaceMountSchema,
  CreateWorkspaceRequestSchema,
  WorkspaceSchema,
  ExecRequestSchema,
  ExecResultSchema,
  ExecStreamAckSchema,
  TerminalFrameSchema as SandboxTerminalFrameSchema,
  TerminalRingResponseSchema,
  WorkspaceListSchema,
  TASK_BRANCH_PATTERN,
  WORKTREE_VOLUME_PATTERN,
  EnsureRepoRequestSchema,
  EnsureRepoResponseSchema,
  ProvisionWorktreeRequestSchema,
  ProvisionWorktreeResponseSchema,
  IngestSourceSchema,
  IngestRepoRequestSchema,
  IngestRepoResponseSchema,
  MergeBranchRequestSchema,
  MergeBranchResponseSchema,
  type CreateWorkspaceRequest,
  type Workspace,
  type ExecRequest,
  type ExecResult,
  type SandboxTerminalFrame,
  type TerminalRingResponse,
  type EnsureRepoRequest,
  type EnsureRepoResponse,
  type ProvisionWorktreeRequest,
  type ProvisionWorktreeResponse,
  type IngestSource,
  type IngestRepoRequest,
  type IngestRepoResponse,
  type MergeBranchRequest,
  type MergeBranchResponse,
} from "./sandbox.js";
export {
  ToolInvokeWireRequestSchema,
  ToolInvokeWireResponseSchema,
  type ToolInvokeWireRequest,
  type ToolInvokeWireResponse,
} from "./tool-invoke.js";
export {
  ToolPermissionItemSchema,
  GrantToolPermissionRequestSchema,
  ToolDefinitionSchema,
  type ToolPermissionItem,
  type GrantToolPermissionRequest,
  type ToolDefinition,
} from "./tools.js";
export {
  TerminalSessionDtoSchema,
  TerminalListQuerySchema,
  TerminalListResponseSchema,
  type TerminalSessionDto,
  type TerminalListResponse,
} from "./terminals.js";
export {
  ReviewDtoSchema,
  ReviewListResponseSchema,
  ReviewDiffResponseSchema,
  type ReviewDto,
  type ReviewListResponse,
  type ReviewDiffResponse,
} from "./reviews.js";
export {
  CostSummaryResponseSchema,
  CostEntriesResponseSchema,
  CostForecastResponseSchema,
  LlmUsageResponseSchema,
  ReportListResponseSchema,
  ExecutiveReportDtoSchema,
  type CostSummaryResponse,
  type CostEntriesResponse,
  type CostForecastResponse,
  type LlmUsageResponse,
  type ReportListResponse,
  type ExecutiveReportDto,
} from "./costs.js";
export {
  MemoryDtoSchema,
  MemoryListResponseSchema,
  MemoryDetailResponseSchema,
  MemoryGraphResponseSchema,
  ContradictionQueueResponseSchema,
  ResolveContradictionRequestSchema,
  FounderMemoryPatchSchema,
  FounderMemoryPatchResponseSchema,
  type MemoryDto,
  type MemoryListResponse,
  type MemoryDetailResponse,
  type MemoryGraphResponse,
  type ContradictionQueueResponse,
  type ResolveContradictionRequest,
  type FounderMemoryPatch,
  type FounderMemoryPatchResponse,
} from "./memories.js";
export {
  SkillMatrixRowSchema,
  SkillMatrixResponseSchema,
  SkillEvidenceDtoSchema,
  SkillEvidenceResponseSchema,
  SkillCandidateSchema,
  SkillCandidatesResponseSchema,
  PromoteSkillRequestSchema,
  PromoteSkillResponseSchema,
  type SkillMatrixRow,
  type SkillMatrixResponse,
  type SkillEvidenceDto,
  type SkillEvidenceResponse,
  type SkillCandidate,
  type SkillCandidatesResponse,
  type PromoteSkillRequest,
  type PromoteSkillResponse,
} from "./skills.js";
export {
  ProjectDtoSchema,
  CreateProjectRequestSchema,
  ProjectListResponseSchema,
  ArtifactDtoSchema,
  type ProjectDto,
  type CreateProjectRequest,
  type ProjectListResponse,
  type ArtifactDto,
} from "./projects.js";
export {
  ApprovalBriefSchema,
  ApprovalKindSchema,
  ApprovalStatusSchema,
  ApprovalUrgencySchema,
  ApprovalRiskSchema,
  ApprovalChainEntrySchema,
  ApprovalSchema,
  ApprovalDetailSchema,
  ApprovalListQuerySchema,
  ApprovalVerdictRequestSchema,
  type ApprovalBrief,
  type Approval,
  type ApprovalDetail,
  type ApprovalVerdictRequest,
} from "./approvals.js";
export {
  AgentSchema,
  AgentStatusSchema,
  SenioritySchema,
  BindingPurposeSchema,
  HireAgentRequestSchema,
  UpdateAgentRequestSchema,
  ChangeAgentPlacementRequestSchema,
  type ChangeAgentPlacementRequest,
  LifecycleActionRequestSchema,
  ModelBindingSchema,
  SetModelBindingRequestSchema,
  AgentSessionSchema,
  AgentStepSchema,
  CompanyAgentSessionSchema,
  type Agent,
  type AgentStep,
  type CompanyAgentSession,
  type ModelBinding,
} from "./agents.js";
